name: Update Calendars

on:
  push:
    branches:
      - main  # Adjust this branch name as needed

jobs:
  update_calendars:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Current Year Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.calendar.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_calendar: yes

      - name: Update Full History Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.calendar.full.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 0

      - name: Commit files
        run: |
          git config --local user.email "elavarasa.003@gmail.com"
          git config --local user.name "Prince"
          git add .
          git commit -m "docs: Update calendars"
          git pull --rebase --autostash

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
