name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Update Metrics
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Detailed display
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.achievements.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_achievements: yes
        plugin_achievements_only: sponsor, maintainer, octonaut

    - name: Compact display
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.achievements.compact.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_achievements: yes
        plugin_achievements_only: polyglot, stargazer, sponsor, deployer, member, maintainer, developer, scripter, packager, explorer, infographile, manager
        plugin_achievements_display: compact
        plugin_achievements_threshold: 10

    - name: Check status and diff
      run: |
        git status
        git diff

    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Commit & Push
      run: |
        git add .
        git commit -m "generated"
        git pull origin ${{ github.ref }} --rebase
        git push origin ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USERNAME: ${{ github.repository_owner }}
