# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.terminal.svg
          # Current configuration doesn't require a GitHub token
          token: NOT_NEEDED

          # Options
          user: follow-prince
          template: classic
          base: ""
          config_timezone: Asia/Calcutta
          plugin_leetcode: yes
          plugin_leetcode_limit_recent: 5
          plugin_leetcode_limit_skills: 10
          plugin_leetcode_sections: solved
          plugin_leetcode_user: iam-prince
          plugin_rss: yes
          plugin_rss_limit: 6
          plugin_rss_source: https://elavarasan.me/feed
          plugin_stackoverflow: yes
          plugin_stackoverflow_limit: 2
          plugin_stackoverflow_lines: 4
          plugin_stackoverflow_lines_snippet: 2
          plugin_stackoverflow_sections: answers-top, questions-recent
          plugin_stackoverflow_user: 20083147
