name: Update WakaTime Stats

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  update_wakatime_stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update WakaTime Stats
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.wakatime.svg
          token: NOT_NEEDED
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}

      - name: Commit files
        run: |
          git config --local user.email "elavarasa.003@gmail.com"
          git config --local user.name "Prince"
          git add .
          git commit -m "docs: Update WakaTime stats"
          git pull --rebase --autostash

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
